# Generated by Django 5.2.4 on 2025-08-26 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'User-created Category',
                'verbose_name_plural': 'User-created Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='learninggoal',
            options={'verbose_name': 'Learning Goal', 'verbose_name_plural': 'Learning Goals'},
        ),
        migrations.AlterModelOptions(
            name='learningmaintopic',
            options={'verbose_name': 'Learning Main Topic', 'verbose_name_plural': 'Learning Main Topics'},
        ),
        migrations.AlterModelOptions(
            name='learningsubtopic',
            options={'verbose_name': 'Learning Sub Topic', 'verbose_name_plural': 'Learning Sub Topics'},
        ),
        migrations.AlterModelOptions(
            name='userinterestcategory',
            options={'verbose_name': 'User Interest Category', 'verbose_name_plural': 'User Interest Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='userinterestcategory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userinterestcategory',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='unique_user_interest_category'),
        ),
        migrations.AddField(
            model_name='usercategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usercategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_category'),
        ),
    ]
