# Generated by Django 5.2.4 on 2025-09-04 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_category_is_global_category_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsubtopic',
            name='learning_goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task_management.learninggoal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningsubtopic',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
