# Generated by Django 5.2.4 on 2025-08-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interest_categories',
            field=models.ManyToManyField(related_name='interested_users', through='task_management.UserInterestCategory', to='task_management.category'),
        ),
    ]
